// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jtjptpukarkqtnwxkdte.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp0anB0cHVrYXJrcXRud3hrZHRlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2MDU3MzUsImV4cCI6MjA2NzE4MTczNX0.jP6lQqAd2DJ9Pq6MXUF5_IDwIYAbgGNgZAtPpubpVmQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});